And/pfn 2 upload download files
eduNEXT/edx-app-android pull request #1
Opened 2018-07-12 17:15 UTC by andrey-canon

## Description
#### (Internal Review)
This PR adds the necessary changes to support SGA in edx android application. Includes the following:
- Add method  onShowFileChooser to upload files.
- Add a listener to download a file
- Modify class IDownloadManagerImpl to make download with cookies 

## Reviewers 
- [ ] @jfavellar90 
- [ ] @Ivanca

2018-07-12 17:42 UTC, Ivanca requested changes
Seria bueno que comenzara a usar un Linter de Java por que veo hay muchas inconsistencias (algunos `if` tienen espacio antes del parentesis inicial, otros no), hay herramientas para arreglar eso automaticamente tales como https://github.com/google/google-java-format e igualmente hay plugins para Sublime Text tales como https://github.com/kauboy26/LimeStyle

2018-07-12 17:42 UTC, Ivanca commented on OpenEdXMobile/src/main/java/org/edx/mobile/view/CourseUnitNavigationActivity.java
> +            Uri[] result = data == null || resultCode != Activity.RESULT_OK ? null
Esta parte esta ilegible, cuando un ternario (`?:`) resulta en una linea tan larga debe mejor usarse un `if`.
En este deberia comenzar asignado a null y luego un if checar si lo llena con el resultado deseado, algo asi:
```java
Uri[] result = null;
if (data != null && resultCode == Activity.RESULT_OK) {
    result = new Uri[]{Uri.parse(data.getDataString())};
}

2018-07-12 17:42 UTC, Ivanca commented on OpenEdXMobile/src/main/java/org/edx/mobile/view/CourseUnitNavigationActivity.java
> +            if (uploadMessage==null) return;
If innecesario, por que puede añadirle a la condicion de arriba esta condicion, osea remplazar la linea 76 con
```java
if (requestCode==FILECHOOSER_RESULTCODE) && uploadMessage != null)

2018-07-13 17:00 UTC, andrey-canon commented
@Ivanca I have included some of your suggestions, please review the changes

2018-07-13 17:03 UTC, Ivanca approved these changes

2018-07-13 23:21 UTC, merged